"""
Clinical Disclaimers and Educational Context Module
Professional disclaimers and educational statements for clinical training system
"""

import streamlit as st
from typing import Dict, List

class ClinicalDisclaimers:
    """Manages clinical disclaimers and educational context throughout the system"""
    
    def __init__(self):
        self.disclaimers = self._define_clinical_disclaimers()
        self.educational_contexts = self._define_educational_contexts()
    
    def _define_clinical_disclaimers(self) -> Dict[str, str]:
        """Define comprehensive clinical disclaimers for different contexts"""
        return {
            "primary": """
            ⚠️ **FOR EDUCATIONAL USE ONLY** - This system is designed exclusively for medical education 
            and training purposes. It is NOT intended for clinical decision-making without supervision 
            by qualified healthcare professionals. All diagnostic outputs must be verified by licensed 
            clinicians before any clinical action is taken.
            """,
            
            "diagnostic": """
            **CLINICAL DISCLAIMER:** This diagnostic analysis is generated by an AI system for educational 
            purposes only. The results should not be used for patient care decisions without review and 
            validation by a qualified healthcare provider. Clinical correlation with patient presentation 
            and additional diagnostic tests is essential.
            """,
            
            "training": """
            **EDUCATIONAL CONTEXT:** This training platform provides simulated clinical scenarios for 
            learning purposes. While based on real clinical data, these cases are designed for educational 
            skill development and should not replace supervised clinical experience or formal medical training.
            """,
            
            "competency": """
            **COMPETENCY ASSESSMENT DISCLAIMER:** Assessment results are intended for educational feedback 
            and skill development tracking. These evaluations do not constitute formal clinical competency 
            certification and should be supplemented with direct clinical supervision and formal evaluation 
            by qualified faculty.
            """,
            
            "research": """
            **RESEARCH AND VALIDATION:** This system is based on validated datasets and evidence-based 
            clinical guidelines. However, ongoing research and clinical validation are required. Educational 
            institutions should conduct their own validation studies appropriate to their specific 
            educational context and student population.
            """,
            
            "limitations": """
            **SYSTEM LIMITATIONS:** This AI system has known limitations including but not limited to: 
            82.1% overall diagnostic accuracy, potential for false positives/negatives, requirement for 
            quality ECG input data, and need for clinical context integration. Users must understand 
            these limitations for appropriate educational use.
            """,
            
            "privacy": """
            **PRIVACY AND DATA PROTECTION:** All ECG data used in this system is de-identified and sourced 
            from publicly available research databases. No patient identifiable information is stored or 
            processed. Educational use should comply with institutional privacy and data protection policies.
            """,
            
            "supervision": """
            **FACULTY SUPERVISION REQUIRED:** This educational tool requires oversight by qualified clinical 
            faculty or healthcare professionals. Students should not use this system independently for 
            clinical learning without appropriate supervision and educational context provided by instructors.
            """
        }
    
    def _define_educational_contexts(self) -> Dict[str, Dict]:
        """Define educational context statements for different learning scenarios"""
        return {
            "dnp_program": {
                "title": "Doctor of Nursing Practice Education",
                "context": """
                This platform is specifically designed to support DNP Essential competencies development 
                through advanced cardiovascular assessment training. Content aligns with current evidence-based 
                practice guidelines and supports the development of expert-level clinical reasoning skills 
                required for advanced practice nursing.
                """,
                "competencies": [
                    "Scientific Foundation for Practice",
                    "Organizational and Systems Leadership",
                    "Clinical Scholarship and Analytical Methods",
                    "Information Systems/Technology",
                    "Health Care Policy for Advocacy",
                    "Interprofessional Collaboration",
                    "Clinical Prevention and Population Health",
                    "Advanced Nursing Practice"
                ]
            },
            
            "medical_education": {
                "title": "Medical Education Integration",
                "context": """
                This system provides comprehensive ECG interpretation training suitable for medical students, 
                residents, and continuing medical education. Content is based on current clinical practice 
                guidelines and provides evidence-based diagnostic criteria appropriate for physician training.
                """,
                "learning_objectives": [
                    "Advanced ECG pattern recognition",
                    "Clinical correlation and decision-making",
                    "Evidence-based diagnostic criteria application",
                    "Risk stratification and treatment planning"
                ]
            },
            
            "nursing_education": {
                "title": "Nursing Education Application",
                "context": """
                Designed for nursing students and practicing nurses developing advanced cardiovascular 
                assessment skills. Emphasizes clinical recognition, priority assessment, and appropriate 
                response protocols within nursing scope of practice.
                """,
                "nursing_focus": [
                    "Clinical assessment and monitoring",
                    "Priority identification and triage",
                    "Interprofessional communication",
                    "Patient safety and quality care"
                ]
            }
        }
    
    def display_primary_disclaimer(self):
        """Display the primary clinical disclaimer"""
        st.warning(self.disclaimers["primary"])
    
    def display_diagnostic_disclaimer(self):
        """Display disclaimer for diagnostic results"""
        st.info(self.disclaimers["diagnostic"])
    
    def display_training_context(self):
        """Display educational training context"""
        st.info(self.disclaimers["training"])
    
    def display_competency_disclaimer(self):
        """Display competency assessment disclaimer"""
        st.warning(self.disclaimers["competency"])
    
    def display_system_limitations(self):
        """Display comprehensive system limitations"""
        with st.expander("System Limitations and Important Information"):
            st.warning(self.disclaimers["limitations"])
            st.info(self.disclaimers["research"])
            st.success(self.disclaimers["privacy"])
            st.error(self.disclaimers["supervision"])
    
    def display_dnp_educational_context(self):
        """Display DNP-specific educational context"""
        dnp_context = self.educational_contexts["dnp_program"]
        
        st.markdown(f"### {dnp_context['title']}")
        st.info(dnp_context["context"])
        
        with st.expander("DNP Essential Competencies Addressed"):
            for competency in dnp_context["competencies"]:
                st.write(f"✓ {competency}")
    
    def display_comprehensive_disclaimers(self):
        """Display all disclaimers in a comprehensive format"""
        st.markdown("## Clinical Disclaimers and Educational Context")
        
        # Primary disclaimer - always visible
        self.display_primary_disclaimer()
        
        # Additional disclaimers in expandable sections
        with st.expander("Diagnostic Analysis Disclaimer"):
            st.info(self.disclaimers["diagnostic"])
        
        with st.expander("Educational Training Context"):
            st.info(self.disclaimers["training"])
        
        with st.expander("Competency Assessment Information"):
            st.warning(self.disclaimers["competency"])
        
        with st.expander("System Limitations and Research Basis"):
            st.warning(self.disclaimers["limitations"])
            st.info(self.disclaimers["research"])
        
        with st.expander("Privacy and Data Protection"):
            st.success(self.disclaimers["privacy"])
        
        with st.expander("Faculty Supervision Requirements"):
            st.error(self.disclaimers["supervision"])
    
    def get_disclaimer_for_context(self, context: str) -> str:
        """Get appropriate disclaimer text for specific context"""
        return self.disclaimers.get(context, self.disclaimers["primary"])
    
    def display_footer_disclaimers(self):
        """Display footer disclaimers for all pages"""
        st.markdown("---")
        st.markdown("**Educational Use Only** | **Requires Clinical Supervision** | **Not for Independent Patient Care**")
        st.markdown("*For technical support or clinical questions, contact your educational institution's clinical faculty.*")

# Global instance for easy import
clinical_disclaimers = ClinicalDisclaimers()